version: '3.7'
services: 
  composer:
    build:
      context: .
      dockerfile: ./docker/composer/Dockerfile
    container_name: composer
    working_dir: /sample-ecs-laravel-docker
    volumes:
      - type: bind
        source: ./
        target: /sample-ecs-laravel-docker

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php
    volumes:
      - type: bind
        source: ./
        target: /sample-ecs-laravel-docker
