version: '3.7'
services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php
    volumes:
      - type: bind
        source: ./
        target: /sample-ecs-laravel-docker

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: node
    volumes:
      - type: bind
        source: ./next
        target: /sample-ecs-laravel-docker/next
      - type: volume
        source: node-modules-data
        target: /sample-ecs-laravel-docker/next/node_modules

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        SERVER_NAME: localhost
        PHP_CONTAINER: php
        NODE_CONTAINER: node
    container_name: nginx
    ports:
      - 80:80

  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql

volumes:
  mysql-data:
  node-modules-data:
