version: '3.7'
services:
  composer:
    build:
      context: .
      dockerfile: ./docker/composer/Dockerfile
    container_name: composer
    volumes:
      - type: bind
        source: ./
        target: /sample-ecs-laravel-docker

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php
    volumes:
      - type: bind
        source: ./
        target: /sample-ecs-laravel-docker

  node_builder:
    build:
      context: .
      dockerfile: ./docker/node_builder/Dockerfile
    container_name: node_builder
    volumes:
      - type: bind
        source: ./next
        target: /sample-ecs-laravel-docker/next

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: node
    volumes:
      - type: bind
        source: ./next
        target: /sample-ecs-laravel-docker/next

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        SERVER_NAME: localhost
        PHP_CONTAINER: php
        NODE_CONTAINER: node
    container_name: nginx
    ports:
      - 80:80
